---
- name: Ensure PostgreSQL Python libraries are installed.
  ansible.builtin.apt:
    name: "{{ postgresql_python_library }}"
    state: present
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success

- name: Ensure PostgreSQL packages are installed.
  ansible.builtin.apt:
    name: "{{ postgresql_packages }}"
    state: present
  register: __pkg_result
  retries: 12
  delay: 10
  until: __pkg_result is success

- name: Ensure all configured locales are present.
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: Force-restart PostgreSQL after new locales are generated.
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: restarted
  when: locale_gen_result.changed
